#!/usr/bin/env node
// characters.mjs — 20 recruitable characters and NPCs.

export function buildCharacters() {
  return [
    // Recruits (early game)
    { id: "recruit_diego_arce_001", name: "Diego de Arce", role: "recruit", rankId: "bisono", portraitAssetId: "asset_portrait_piquero_001", bio: "Bisoño castellano, sin oficio de guerra. Aprende rápido o muere.", stats: { pike: 2, sword: 1, arquebus: 0, discipline: 1, vigor: 2, cunning: 1, command: 0 }, startingItems: ["weapon_pica_gastada_001"], tags: ["starter", "pike"] },
    { id: "recruit_juan_lerma_001", name: "Juan de Lerma", role: "recruit", rankId: "bisono", portraitAssetId: "asset_portrait_recluta_joven_001", bio: "Joven, asustado, despierto. Le tiembla el pulso en el primer disparo.", stats: { pike: 1, sword: 1, arquebus: 1, discipline: 1, vigor: 2, cunning: 2, command: 0 }, startingItems: ["weapon_daga_001"], tags: ["starter", "cunning"] },
    { id: "recruit_pedro_orellana_001", name: "Pedro de Orellana", role: "recruit", rankId: "bisono", portraitAssetId: "asset_portrait_arcabucero_001", bio: "Tirador bisoño, gasta pólvora sin pensarlo.", stats: { pike: 0, sword: 1, arquebus: 2, discipline: 1, vigor: 1, cunning: 2, command: 0 }, startingItems: ["weapon_arcabuz_bisono_001"], tags: ["starter", "firearm"] },
    // Soldiers
    { id: "soldier_martin_cuenca_001", name: "Martín de Cuenca", role: "soldier", rankId: "soldado", portraitAssetId: "asset_portrait_arcabucero_001", bio: "Tirador fiable, conoce el peso de la pólvora.", stats: { pike: 1, sword: 2, arquebus: 3, discipline: 2, vigor: 2, cunning: 2, command: 0 }, startingItems: ["weapon_mecha_001", "helmet_morion_004"], tags: ["soldier", "firearm"] },
    { id: "soldier_alonso_valdes_001", name: "Alonso de Valdés", role: "soldier", rankId: "soldado", portraitAssetId: "asset_portrait_piquero_001", bio: "Piquero con cuatro campañas a la espalda.", stats: { pike: 3, sword: 2, arquebus: 0, discipline: 3, vigor: 3, cunning: 1, command: 1 }, startingItems: ["weapon_pica_ash_001", "chest_cuirass_004"], tags: ["soldier", "pike", "veteran"] },
    { id: "soldier_sancho_leiva_001", name: "Sancho de Leiva", role: "soldier", rankId: "soldado_viejo", portraitAssetId: "asset_portrait_veterano_001", bio: "Soldado viejo, curtido. Conoce el hambre y la línea.", stats: { pike: 3, sword: 3, arquebus: 1, discipline: 3, vigor: 3, cunning: 2, command: 1 }, startingItems: ["weapon_ancha_flandes_001", "chest_gambeson_u_001"], tags: ["soldier", "veteran", "blade"] },
    { id: "soldier_lope_saavedra_001", name: "Lope de Saavedra", role: "soldier", rankId: "soldado", portraitAssetId: "asset_portrait_arcabucero_001", bio: "Tirador de ojo fino. Carga con calma.", stats: { pike: 1, sword: 2, arquebus: 3, discipline: 2, vigor: 2, cunning: 3, command: 0 }, startingItems: ["weapon_piston_001", "boots_official_001"], tags: ["soldier", "firearm"] },
    { id: "soldier_gines_mendoza_001", name: "Ginés de Mendoza", role: "soldier", rankId: "soldado_viejo", portraitAssetId: "asset_portrait_piquero_001", bio: "Piquero fuerte, mejor con la pica que con la pluma.", stats: { pike: 4, sword: 2, arquebus: 0, discipline: 3, vigor: 4, cunning: 1, command: 0 }, startingItems: ["weapon_pica_haya_001", "chest_cuirass_005"], tags: ["soldier", "pike", "veteran"] },
    // NPC: Cabo
    { id: "npc_cabo_garcia_001", name: "García de Aguilar", role: "soldier", rankId: "cabo_de_escuadra", portraitAssetId: "asset_portrait_cabo_001", bio: "Cabo de escuadra. Voz que se oye entre el humo.", stats: { pike: 3, sword: 3, arquebus: 1, discipline: 4, vigor: 3, cunning: 2, command: 2 }, startingItems: ["weapon_cazoleta_001", "chest_cuirass_rare_001"], tags: ["npc", "cabo", "officer"] },
    // NPC: Sargento
    { id: "npc_sargento_ordas_001", name: "Ordas el Viejo", role: "soldier", rankId: "sargento", portraitAssetId: "asset_portrait_sargento_001", bio: "Sargento con cicatrices y memoria larga.", stats: { pike: 3, sword: 4, arquebus: 2, discipline: 4, vigor: 4, cunning: 2, command: 3 }, startingItems: ["weapon_toledo_001", "chest_cuirass_rare_002"], tags: ["npc", "sargento", "officer"] },
    // NPC: Capitán
    { id: "npc_capitan_moncada_001", name: "Moncada de Alarcón", role: "captain", rankId: "capitan", portraitAssetId: "asset_portrait_capitan_001", bio: "Capitán de la compañía. Pesa más que su espada.", stats: { pike: 4, sword: 4, arquebus: 2, discipline: 4, vigor: 4, cunning: 3, command: 4 }, startingItems: ["weapon_maestre_001", "chest_cuirass_master_001"], tags: ["npc", "captain", "masterwork"] },
    // NPC: Maestre de campo
    { id: "npc_maestre_alba_001", name: "Duque de Alba", role: "captain", rankId: "maestre_de_campo", portraitAssetId: "asset_portrait_capitan_001", bio: "Maestre de campo. Su firma vale una vida.", stats: { pike: 4, sword: 4, arquebus: 3, discipline: 5, vigor: 4, cunning: 4, command: 5 }, startingItems: ["weapon_maestre_001", "chest_cuirass_master_001"], tags: ["npc", "maestre", "command"] },
    // NPC: Cirujano
    { id: "npc_cirujano_morales_001", name: "Morales el Cirujano", role: "surgeon", rankId: "cabo", portraitAssetId: "asset_portrait_cirujano_001", bio: "Cirujano de campaña. Más vale su aguja que un sermón.", stats: { pike: 0, sword: 1, arquebus: 0, discipline: 3, vigor: 2, cunning: 4, command: 1 }, startingItems: ["consumable_vendas_001", "consumable_unguento_001", "consumable_aguja_001"], tags: ["npc", "surgeon"] },
    // NPC: Capellán
    { id: "npc_capellan_pablo_001", name: "Padre Pablo de Olavide", role: "chaplain", rankId: "cabo", portraitAssetId: "asset_portrait_capellan_001", bio: "Capellán del tercio. Reza, reza y reza.", stats: { pike: 0, sword: 1, arquebus: 0, discipline: 4, vigor: 2, cunning: 2, command: 2 }, startingItems: ["religious_cruz_001", "religious_rosario_001", "consumable_vino_001"], tags: ["npc", "chaplain"] },
    // NPC: Intendente
    { id: "npc_intendente_urrutia_001", name: "Urrutia el Intendente", role: "quartermaster", rankId: "cabo", portraitAssetId: "asset_portrait_intendente_001", bio: "Intendente, lleva los libros y el pan. Cobra su parte.", stats: { pike: 0, sword: 0, arquebus: 0, discipline: 3, vigor: 2, cunning: 5, command: 1 }, startingItems: ["trinket_mapa_001", "consumable_pan_duro_001"], tags: ["npc", "quartermaster"] },
    // Reclutas adicionales
    { id: "recruit_maria_cordero_001", name: "María Cordero", role: "recruit", rankId: "bisono", portraitAssetId: "asset_portrait_piquero_001", bio: "Mozuela que se alista con su padre. Carga más de lo que dice.", stats: { pike: 1, sword: 2, arquebus: 0, discipline: 2, vigor: 2, cunning: 2, command: 0 }, startingItems: ["weapon_daga_001"], tags: ["recruit", "cunning"] },
    { id: "recruit_hernan_cortes_001", name: "Hernán Cortés", role: "recruit", rankId: "bisono", portraitAssetId: "asset_portrait_recluta_joven_001", bio: "Joven de Cáceres, ansioso por la paga y el honor.", stats: { pike: 2, sword: 1, arquebus: 1, discipline: 1, vigor: 3, cunning: 1, command: 0 }, startingItems: ["weapon_pica_corta_001"], tags: ["recruit", "pike"] },
    { id: "recruit_bruno_toledo_001", name: "Bruno de Toledo", role: "recruit", rankId: "bisono", portraitAssetId: "asset_portrait_arcabucero_001", bio: "Aprendiz de armero, tira mejor de lo que limpia.", stats: { pike: 0, sword: 1, arquebus: 2, discipline: 1, vigor: 2, cunning: 2, command: 0 }, startingItems: ["weapon_mosquete_001"], tags: ["recruit", "firearm"] },
    { id: "recruit_ana_olivares_001", name: "Ana de Olivares", role: "recruit", rankId: "bisono", portraitAssetId: "asset_portrait_piquero_001", bio: "Viuda de soldado. Vuelve al tercio a cobrar lo que deben.", stats: { pike: 1, sword: 2, arquebus: 0, discipline: 3, vigor: 2, cunning: 2, command: 1 }, startingItems: ["weapon_ropera_ronosa_001"], tags: ["recruit", "discipline"] },
    { id: "recruit_jacobo_ruiz_001", name: "Jacobo Ruiz", role: "recruit", rankId: "bisono", portraitAssetId: "asset_portrait_recluta_joven_001", bio: "Capataz de campo, sabe más de hambre que de guerra.", stats: { pike: 1, sword: 1, arquebus: 0, discipline: 2, vigor: 3, cunning: 1, command: 0 }, startingItems: ["weapon_pica_gastada_001"], tags: ["recruit", "stamina"] },
    { id: "recruit_mencia_flores_001", name: "Mencia Flores", role: "recruit", rankId: "bisono", portraitAssetId: "asset_portrait_piquero_001", bio: "Sirvienta del convento antes que del tercio. Sabe obedecer.", stats: { pike: 2, sword: 1, arquebus: 0, discipline: 3, vigor: 2, cunning: 1, command: 0 }, startingItems: ["weapon_pica_corta_001"], tags: ["recruit", "discipline"] },
  ];
}
