#!/usr/bin/env node
// enemies.mjs — define 24 enemies across regions and difficulty tiers.

export function buildEnemies() {
  return [
    // Level 1-2 (early road/camp)
    { id: "enemy_bandolero_camino_001", name: "Bandolero de camino", description: "Humano, sucio, peligroso por hambre más que por gloria.", level: 1, region: "castilla", assetId: "asset_enemy_bandolero_001", stats: { pike: 1, sword: 2, arquebus: 0, discipline: 0, vigor: 2, cunning: 2, command: 0, armor: 0, damageMin: 1, damageMax: 4 }, rewards: { xp: 6, coinsMin: 1, coinsMax: 5, honor: 0 }, tags: ["human", "low_level"] },
    { id: "enemy_desertor_001", name: "Desertor hambriento", description: "Hombre que conoce la línea y prefiere comer.", level: 1, region: "castilla", assetId: "asset_enemy_desertor_001", stats: { pike: 1, sword: 1, arquebus: 0, discipline: 0, vigor: 1, cunning: 1, command: 0, armor: 0, damageMin: 1, damageMax: 3 }, rewards: { xp: 5, coinsMin: 1, coinsMax: 4, honor: 0 }, tags: ["human", "low_level"] },
    { id: "enemy_salteador_001", name: "Salteador de caminos", description: "Cuchillo rápido cerca de carros rotos.", level: 2, region: "castilla", assetId: "asset_enemy_bandolero_001", stats: { pike: 0, sword: 3, arquebus: 0, discipline: 0, vigor: 2, cunning: 3, command: 0, armor: 0, damageMin: 1, damageMax: 5 }, rewards: { xp: 8, coinsMin: 2, coinsMax: 7, honor: 0 }, tags: ["human", "road"] },
    { id: "enemy_ladron_polvora_001", name: "Ladrón de pólvora", description: "Hombre flaco que prefiere cortar mechas y desaparecer.", level: 2, region: "castilla", assetId: "asset_enemy_bandolero_001", stats: { pike: 0, sword: 2, arquebus: 0, discipline: 0, vigor: 1, cunning: 4, command: 0, armor: 0, damageMin: 1, damageMax: 3 }, rewards: { xp: 7, coinsMin: 1, coinsMax: 5, honor: 0 }, tags: ["human", "cunning"] },
    { id: "enemy_paisano_001", name: "Paisano con horca", description: "Aldeano con herramientas de campo. No sabe alinearse.", level: 1, region: "castilla", assetId: "asset_enemy_bandolero_001", stats: { pike: 2, sword: 0, arquebus: 0, discipline: 0, vigor: 1, cunning: 0, command: 0, armor: 0, damageMin: 1, damageMax: 3 }, rewards: { xp: 4, coinsMin: 0, coinsMax: 2, honor: -1 }, tags: ["human", "low_level"] },
    // Level 3-4 (camp, patrol, forest)
    { id: "enemy_escaramuza_frances_001", name: "Escaramuzador francés", description: "Tirador suelto, dispara y se repliega.", level: 3, region: "flandes", assetId: "asset_enemy_oficial_001", stats: { pike: 0, sword: 1, arquebus: 3, discipline: 1, vigor: 2, cunning: 3, command: 0, armor: 0, damageMin: 1, damageMax: 6 }, rewards: { xp: 12, coinsMin: 3, coinsMax: 8, honor: 1 }, tags: ["human", "firearm"] },
    { id: "enemy_escaramuza_protestante_001", name: "Escaramuzador protestante", description: "Disparos dispersos entre setos húmedos.", level: 3, region: "flandes", assetId: "asset_enemy_oficial_001", stats: { pike: 0, sword: 1, arquebus: 3, discipline: 1, vigor: 2, cunning: 3, command: 0, armor: 0, damageMin: 2, damageMax: 6 }, rewards: { xp: 13, coinsMin: 3, coinsMax: 8, honor: 1 }, tags: ["human", "firearm", "flandes"] },
    { id: "enemy_veterano_mutin_001", name: "Veterano amotinado", description: "Sin paga, aún recuerda cerrar la línea.", level: 4, region: "campamento", assetId: "asset_enemy_oficial_001", stats: { pike: 3, sword: 3, arquebus: 1, discipline: 2, vigor: 3, cunning: 2, command: 1, armor: 1, damageMin: 2, damageMax: 7 }, rewards: { xp: 18, coinsMin: 4, coinsMax: 12, honor: 0 }, tags: ["human", "mutiny", "veteran"] },
    { id: "enemy_jinete_001", name: "Jinete ligero", description: "A caballo, lanza corta. Ataca y se aleja.", level: 4, region: "castilla", assetId: "asset_enemy_oficial_001", stats: { pike: 2, sword: 3, arquebus: 0, discipline: 2, vigor: 3, cunning: 2, command: 0, armor: 1, damageMin: 2, damageMax: 7 }, rewards: { xp: 16, coinsMin: 3, coinsMax: 10, honor: 1 }, tags: ["human", "cavalry"] },
    { id: "enemy_guardia_bosque_001", name: "Guardia del bosque", description: "Vigilante local, conoce los senderos.", level: 3, region: "campamento", assetId: "asset_enemy_bandolero_001", stats: { pike: 1, sword: 2, arquebus: 2, discipline: 1, vigor: 2, cunning: 3, command: 0, armor: 0, damageMin: 1, damageMax: 5 }, rewards: { xp: 10, coinsMin: 2, coinsMax: 6, honor: 0 }, tags: ["human", "forest"] },
    // Level 5-6 (convoy, trench, siege, Italy)
    { id: "enemy_piquero_italiano_001", name: "Piquero italiano", description: "Pica larga, mejor formación. Sabe esperar.", level: 5, region: "italia", assetId: "asset_enemy_oficial_001", stats: { pike: 4, sword: 2, arquebus: 0, discipline: 3, vigor: 3, cunning: 1, command: 1, armor: 1, damageMin: 3, damageMax: 8 }, rewards: { xp: 24, coinsMin: 5, coinsMax: 14, honor: 2 }, tags: ["human", "pike", "italy"] },
    { id: "enemy_arcabucero_italiano_001", name: "Arcabucero italiano", description: "Tiro fiable, parapeto bajo.", level: 5, region: "italia", assetId: "asset_enemy_oficial_001", stats: { pike: 0, sword: 1, arquebus: 5, discipline: 2, vigor: 2, cunning: 3, command: 0, armor: 1, damageMin: 3, damageMax: 9 }, rewards: { xp: 24, coinsMin: 5, coinsMax: 14, honor: 2 }, tags: ["human", "firearm", "italy"] },
    { id: "enemy_cabo_camino_001", name: "Capitán del camino", description: "Jefe de cuadrilla con mapa y demasiados hombres.", level: 5, region: "flandes", assetId: "asset_enemy_oficial_001", stats: { pike: 2, sword: 4, arquebus: 2, discipline: 2, vigor: 3, cunning: 4, command: 2, armor: 1, damageMin: 3, damageMax: 9 }, rewards: { xp: 28, coinsMin: 8, coinsMax: 18, honor: 2 }, tags: ["human", "boss", "flandes"] },
    { id: "enemy_emboscador_polvora_001", name: "Emboscador de pólvora", description: "Arcabucero paciente, experto en esperar la chispa.", level: 5, region: "flandes", assetId: "asset_enemy_oficial_001", stats: { pike: 0, sword: 1, arquebus: 5, discipline: 2, vigor: 2, cunning: 4, command: 0, armor: 0, damageMin: 4, damageMax: 10 }, rewards: { xp: 26, coinsMin: 6, coinsMax: 14, honor: 2 }, tags: ["human", "firearm", "flandes", "boss"] },
    { id: "enemy_mercenario_001", name: "Mercenario del cruce", description: "Vende su espada por plata, pelea como si le debieran una corona.", level: 6, region: "flandes", assetId: "asset_enemy_oficial_001", stats: { pike: 3, sword: 4, arquebus: 1, discipline: 3, vigor: 4, cunning: 2, command: 1, armor: 2, damageMin: 3, damageMax: 10 }, rewards: { xp: 30, coinsMin: 6, coinsMax: 16, honor: 1 }, tags: ["human", "mercenary"] },
    { id: "enemy_piquero_sitio_001", name: "Piquero de sitio", description: "Defiende la trinchera con disciplina.", level: 6, region: "asedio", assetId: "asset_enemy_oficial_001", stats: { pike: 5, sword: 2, arquebus: 0, discipline: 4, vigor: 4, cunning: 1, command: 1, armor: 2, damageMin: 3, damageMax: 9 }, rewards: { xp: 30, coinsMin: 5, coinsMax: 12, honor: 2 }, tags: ["human", "pike", "siege"] },
    { id: "enemy_artillero_001", name: "Artillero de campaña", description: "Sirve un falconete ligero. Muro o carne.", level: 6, region: "asedio", assetId: "asset_enemy_oficial_001", stats: { pike: 0, sword: 1, arquebus: 6, discipline: 2, vigor: 3, cunning: 2, command: 1, armor: 1, damageMin: 5, damageMax: 12 }, rewards: { xp: 32, coinsMin: 8, coinsMax: 20, honor: 2 }, tags: ["human", "siege", "artillery"] },
    // Level 7-9 (boss tier)
    { id: "enemy_oficial_mayor_001", name: "Oficial mayor", description: "Oficial duro, criado entre parapetos.", level: 7, region: "flandes", assetId: "asset_enemy_oficial_001", stats: { pike: 3, sword: 5, arquebus: 2, discipline: 4, vigor: 4, cunning: 3, command: 3, armor: 3, damageMin: 4, damageMax: 10 }, rewards: { xp: 38, coinsMin: 8, coinsMax: 18, honor: 3 }, tags: ["human", "officer", "boss"] },
    { id: "enemy_mercenario_veterano_001", name: "Mercenario veterano", description: "Veterano que pelea por oro y odio.", level: 7, region: "italia", assetId: "asset_enemy_oficial_001", stats: { pike: 3, sword: 5, arquebus: 3, discipline: 4, vigor: 5, cunning: 3, command: 2, armor: 3, damageMin: 4, damageMax: 11 }, rewards: { xp: 40, coinsMin: 8, coinsMax: 20, honor: 3 }, tags: ["human", "mercenary", "boss"] },
    { id: "enemy_caballero_negro_001", name: "Caballero acorazado", description: "Coraza completa, monta enorme. Carga la línea.", level: 8, region: "italia", assetId: "asset_enemy_oficial_001", stats: { pike: 4, sword: 5, arquebus: 0, discipline: 3, vigor: 5, cunning: 2, command: 2, armor: 5, damageMin: 5, damageMax: 12 }, rewards: { xp: 45, coinsMin: 10, coinsMax: 24, honor: 4 }, tags: ["human", "cavalry", "boss"] },
    { id: "enemy_comandante_baluarte_001", name: "Comandante del baluarte", description: "Oficial duro, criado entre parapetos, humo bajo y órdenes sin réplica.", level: 9, region: "flandes", assetId: "asset_enemy_oficial_001", stats: { pike: 4, sword: 6, arquebus: 3, discipline: 5, vigor: 5, cunning: 4, command: 4, armor: 4, damageMin: 5, damageMax: 12 }, rewards: { xp: 55, coinsMin: 12, coinsMax: 28, honor: 5 }, tags: ["human", "boss", "flandes", "siege"] },
    { id: "enemy_arquero_montana_001", name: "Arquero de montaña", description: "Tirador de la montaña, dispara y se mueve.", level: 5, region: "italia", assetId: "asset_enemy_oficial_001", stats: { pike: 0, sword: 1, arquebus: 4, discipline: 2, vigor: 3, cunning: 4, command: 0, armor: 0, damageMin: 2, damageMax: 8 }, rewards: { xp: 22, coinsMin: 4, coinsMax: 10, honor: 1 }, tags: ["human", "firearm", "italy"] },
    { id: "enemy_sargento_rebelde_001", name: "Sargento rebelde", description: "Sargento que se pasó al enemigo. Conoce tus tácticas.", level: 6, region: "campamento", assetId: "asset_enemy_oficial_001", stats: { pike: 3, sword: 4, arquebus: 2, discipline: 4, vigor: 4, cunning: 3, command: 3, armor: 2, damageMin: 3, damageMax: 9 }, rewards: { xp: 32, coinsMin: 7, coinsMax: 16, honor: -1 }, tags: ["human", "traitor", "officer"] },
    { id: "enemy_explorador_001", name: "Explorador enemigo", description: "Hombre rápido, ojos en el barro. Reconoce la línea.", level: 3, region: "campamento", assetId: "asset_enemy_bandolero_001", stats: { pike: 0, sword: 2, arquebus: 1, discipline: 1, vigor: 3, cunning: 4, command: 0, armor: 0, damageMin: 1, damageMax: 4 }, rewards: { xp: 9, coinsMin: 1, coinsMax: 4, honor: 0 }, tags: ["human", "scout"] },
  ];
}
