#!/usr/bin/env node
// events.mjs — 30 events with choices and effects. Some mature/blurred.

export function buildEvents() {
  return [
    {
      id: "event_paga_atrasada_001",
      name: "Paga atrasada",
      description: "El pagador trae sellos, excusas y ni una bolsa entera. Los soldados murmuran que Flandes devora hombres y también sus salarios.",
      choices: [
        { id: "aguantar", label: "Aguantar en silencio", effects: { honor: 1, fatigue: 2 }, result_text: "Callas. La línea aguanta." },
        { id: "quejarse", label: "Quejarse al cabo", effects: { honor: -1, coins: 1 }, result_text: "Te oyen. No te pagan más." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["camp", "pay"],
    },
    {
      id: "event_hambre_camino_001",
      name: "Hambre en el camino",
      description: "Los carros de suministros no han llegado y las tripas de tus soldados rugen más fuerte que la artillería.",
      choices: [
        { id: "saquear", label: "Saquear granjas locales", effects: { honor: -3, fatigue: -3, corruption: 8, items: [{ itemId: "consumable_pan_duro_001", quantity: 3 }] }, result_text: "Vuelven con pan y vergüenza." },
        { id: "hurtar", label: "Enviar pajes a hurtar", effects: { honor: -1, coins: -6, corruption: 4, items: [{ itemId: "consumable_pan_duro_001", quantity: 2 }] }, result_text: "Traen algo. Te cuesta." },
        { id: "aguantar", label: "Apretar el cinturón", effects: { fatigue: 8, honor: 2 }, result_text: "Aguantas. El hambre también." },
      ],
      mature: true,
      presentation: "blurred",
      tags: ["road", "hunger", "camp"],
    },
    {
      id: "event_polvora_humeda_001",
      name: "Pólvora húmeda",
      description: "La lluvia entra por las costuras del barril. Los arcabuceros sacuden las mechas y nadie quiere ser el primero en probar si la pólvora prenderá.",
      choices: [
        { id: "secar_fuego", label: "Secarla al fuego", effects: { fatigue: 4, items: [{ itemId: "consumable_piedra_001", quantity: 1 }] }, result_text: "Secas algo. Te quemas un poco." },
        { id: "tirar", label: "Tirar los barriles peores", effects: { honor: 1, fatigue: 2 }, result_text: "Pierdes munición, ganas salud." },
        { id: "vender", label: "Venderla como si estuviera seca", effects: { coins: 8, corruption: 6 }, result_text: "Ganas monedas, huele a azufre." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["camp", "powder"],
    },
    {
      id: "event_rancho_podrid_001",
      name: "Rancho verde y podrido",
      description: "El tocino salado de la ración huele a fango de fosa y el pan tiene manchas verdes de humedad.",
      choices: [
        { id: "forzar", label: "Forzar a la tropa a comer", effects: { wound: "wound_diarrea_001", fatigue: 2 }, result_text: "Comen. Muchos caen con diarrea." },
        { id: "comprar", label: "Comprar raciones frescas", effects: { coins: -8, fatigue: -2 }, result_text: "Pagas, comes caliente." },
        { id: "saquear_iglesia", label: "Saquean el granero de la iglesia", effects: { honor: -3, corruption: 6, items: [{ itemId: "consumable_pan_duro_001", quantity: 2 }] }, result_text: "Vuelven con grano, la iglesia llora." },
      ],
      mature: true,
      presentation: "blurred",
      tags: ["camp", "hunger"],
    },
    {
      id: "event_dados_taberna_001",
      name: "Dados en la taberna",
      description: "Tus soldados están jugando a los dados con unos lugareños. La tensión sube; las manos acarician las dagas.",
      choices: [
        { id: "apoyar_trampa", label: "Apoyar la trampa de tus hombres", effects: { coins: 10, corruption: 6, honor: -1 }, result_text: "Cobráis. Os miran mal." },
        { id: "castigar", label: "Castigar públicamente a los tramposos", effects: { honor: 2, fatigue: 3, corruption: -2 }, result_text: "Los aldeanos asienten, tus hombres reniegan." },
        { id: "pagar_ronda", label: "Jugar limpio y pagar la ronda", effects: { coins: -5, fatigue: -4, honor: 1 }, result_text: "Cerveza agria, ánimos calmados." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["tavern", "dice"],
    },
    {
      id: "event_caravana_bosque_001",
      name: "Caravana en el bosque",
      description: "Una pequeña caravana de mercaderes se ha quedado atascada en el lodo del bosque de Brabante.",
      choices: [
        { id: "tributo", label: "Exigir tributo de paso", effects: { coins: 12, corruption: 6, honor: -1 }, result_text: "Pagan con manos temblando." },
        { id: "saquear", label: "Dejar que la tropa la saquee", effects: { coins: 30, corruption: 16, honor: -4, items: [{ itemId: "consumable_vino_001", quantity: 2 }] }, result_text: "Saqueada. Tu nombre se mancha." },
        { id: "escoltar", label: "Ayudarles y escoltarlos", effects: { honor: 3, fatigue: 6 }, result_text: "Empuñan los carros. Ganas respeto." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["road", "caravan"],
    },
    {
      id: "event_correas_rotas_001",
      name: "Correas rotas y hierro doblado",
      description: "Las correas de tu coraza ceden y la pica da un crujido preocupante al apoyarse en el lodo.",
      choices: [
        { id: "reparar", label: "Pagar repuestos rápidos", effects: { coins: -6, fatigue: 1 }, result_text: "Pagas cuero y brea." },
        { id: "forzar", label: "Forzar la marcha con el equipo dañado", effects: { fatigue: 4, breakEquipment: true }, result_text: "Algo se rompe. En el peor momento." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["camp", "equipment"],
    },
    {
      id: "event_fiebre_camp_001",
      name: "Fiebre de campamento",
      description: "El agua huele a cuero viejo y las mantas nunca llegan a secarse. Al amanecer, varios hombres tiemblan entre los carros.",
      choices: [
        { id: "cirujano", label: "Pagar al cirujano de campaña", effects: { coins: -10, fatigue: -4, items: [{ itemId: "consumable_vendas_001", quantity: 1 }] }, result_text: "El cirujano reparte vendas y vino agrio." },
        { id: "marchar", label: "Marchar pese a la fiebre", effects: { wound: "wound_fiebre_001", fatigue: 6, honor: 1 }, result_text: "Marcha. La fiebre también." },
        { id: "quemar", label: "Quemar mantas y jergones", effects: { fatigue: 4, honor: 1 }, result_text: "Humo negro, aire limpio." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["camp", "fever"],
    },
    {
      id: "event_hurto_camp_001",
      name: "Hurtos en el campamento",
      description: "Despiertas y descubres que alguien ha hurgado en tu fardaje. Faltan varias monedas y un trozo de pan.",
      choices: [
        { id: "castigo", label: "Castigo público ejemplar", effects: { corruption: 8, honor: -2, fatigue: 2 }, result_text: "Todos entienden el mensaje." },
        { id: "registrar", label: "Registrar las tiendas", effects: { coins: 6, fatigue: 5, honor: -1 }, result_text: "Recuperas algo. Tensiones a la vista." },
        { id: "ignorar", label: "Ignorar la afrenta", effects: { coins: -8, honor: 1 }, result_text: "Callas. Asumes la pérdida." },
      ],
      mature: true,
      presentation: "blurred",
      tags: ["camp", "theft"],
    },
    {
      id: "event_disciplina_linea_001",
      name: "Disciplina en la línea",
      description: "Un cabo se adelanta sin orden y arrastra a tres bisoños detrás. La línea se abre justo cuando el enemigo tantea el terreno.",
      choices: [
        { id: "restaurar_dura", label: "Restaurar la línea con dureza", effects: { honor: 2, fatigue: 4 }, result_text: "Tu voz corta el ruido como hierro frío." },
        { id: "cubrir_fuego", label: "Cubrirlos con arcabuces", effects: { fatigue: 6, items: [{ itemId: "consumable_polvora_humeda_001", quantity: 1 }] }, result_text: "Salvas la formación, quemas munición." },
        { id: "premiar_cabo", label: "Premiar al cabo que corrigió", effects: { coins: -6, honor: 1 }, result_text: "Los bisoños aprenden." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["line", "discipline"],
    },
    {
      id: "event_capilla_001",
      name: "Misa en la capilla del campo",
      description: "El capellán dice misa. Media compañía no se atreve a entrar.",
      choices: [
        { id: "asistir", label: "Asistir y dejar que recen", effects: { honor: 2, discipline: 1 }, result_text: "Rezan. La línea está más quieta." },
        { id: "donar", label: "Donar para velas y vino", effects: { coins: -8, honor: 3 }, result_text: "El capellán te nombra en la oración." },
        { id: "rechazar", label: "Decir que la línea no se arrodilla", effects: { honor: -1, discipline: -1 }, result_text: "La tropa se nota más suelta. Y más lejos." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["camp", "religion"],
    },
    {
      id: "event_correo_llegada_001",
      name: "Llega el correo",
      description: "Un muchacho trae cartas y un saco de la intendencia. Las caras se alegran o se apagan.",
      choices: [
        { id: "repartir", label: "Repartir las cartas y los víveres", effects: { honor: 1, discipline: 1 }, result_text: "La tropa abre las cartas." },
        { id: "censurar", label: "Censurar las cartas primero", effects: { corruption: 4, fatigue: 2 }, result_text: "Filtras lo que no conviene." },
        { id: "cobrar", label: "Cobrar el porte del saco", effects: { coins: 6, honor: -1 }, result_text: "Cobras. La tropa te mira mal." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["camp", "mail"],
    },
    {
      id: "event_inspeccion_001",
      name: "Inspección del sargento",
      description: "El sargento revisa correas, picas y pólvora. Algunos hombres esconden lo que pueden.",
      choices: [
        { id: "abrir_todo", label: "Mostrar todo lo que tienes", effects: { honor: 1, fatigue: 2 }, result_text: "Pasa la revista sin notas." },
        { id: "esconder", label: "Esconder lo mejor bajo el petate", effects: { corruption: 4, fatigue: 1 }, result_text: "Lo guardas. El sargento sospecha." },
        { id: "sobornar", label: "Sobornar al sargento con vino", effects: { coins: -6, corruption: 4 }, result_text: "Mira a otro lado." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["camp", "discipline"],
    },
    {
      id: "event_motin_paga_001",
      name: "Motín de la tropa",
      description: "Un grupo de veteranos rodea el cofre de pagas con la intención de tomarlo.",
      choices: [
        { id: "pagar_tu_bolsa", label: "Adelantar paga de tu bolsa", effects: { coins: -12, honor: 3, fatigue: -3 }, result_text: "Repartes doblones. La línea no se rompe." },
        { id: "apretar_pagador", label: "Apretar al pagador contra el carro", effects: { coins: 18, corruption: 8, honor: -1 }, result_text: "El pagador encuentra una bolsa olvidada." },
        { id: "predicar", label: "Pedir paciencia y deber", effects: { honor: 2, fatigue: 8, corruption: -2 }, result_text: "Algunos bajan la cabeza; otros escupen al barro." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["camp", "mutiny", "pay"],
    },
    {
      id: "event_desertor_capturado_001",
      name: "Desertor capturado",
      description: "Los pajes traen a un hombre que se fue con el botín de la última escolta.",
      choices: [
        { id: "azotes_publicos", label: "Azotes públicos", effects: { honor: 1, corruption: 4, fatigue: 2 }, result_text: "La tropa mira. Nadie aplaude." },
        { id: "horca", label: "Horca de campaña", effects: { honor: 2, corruption: 2, fatigue: 4 }, result_text: "Cuelga. La tropa entiende." },
        { id: "perdon", label: "Perdón y degradación", effects: { honor: -2, discipline: -2 }, result_text: "Vuelve a la línea. La disciplina se nota." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["camp", "discipline"],
    },
    {
      id: "event_saqueo_aldea_001",
      name: "Saqueo de aldea",
      description: "Tus hombres quieren entrar en una aldea por leña y grano. El cabo espera tu orden.",
      choices: [
        { id: "permitir", label: "Permitir el saqueo", effects: { coins: 14, corruption: 12, honor: -3, items: [{ itemId: "consumable_salazon_001", quantity: 2 }] }, result_text: "Entran. Vuelven con comida y vergüenza." },
        { id: "limitar", label: "Limitarlo a leña y grano", effects: { coins: 4, corruption: 4, fatigue: 2, items: [{ itemId: "consumable_pan_duro_001", quantity: 2 }] }, result_text: "Limpiado. Casi sin sangre." },
        { id: "prohibir", label: "Prohibirlo bajo pena de muerte", effects: { honor: 3, discipline: 2, fatigue: 4 }, result_text: "Callan. Tus hombres te respetan a disgusto." },
      ],
      mature: true,
      presentation: "blurred",
      tags: ["camp", "loot", "moral"],
    },
    {
      id: "event_duelo_taberna_001",
      name: "Duelo en la taberna",
      description: "Un veterano de otra compañía te ha insultado a ti y a tu sargento. Hay testigos.",
      choices: [
        { id: "aceptar", label: "Aceptar el duelo", effects: { honor: 2, fatigue: 4, wound: "wound_corte_mano_001" }, result_text: "Cruzáis aceros. Ganas el corte y el respeto." },
        { id: "negarse", label: "Negarte", effects: { honor: -2, discipline: -1 }, result_text: "No peleas. Te miran con desprecio." },
        { id: "enviar_cabo", label: "Enviar al cabo en tu lugar", effects: { honor: 1, fatigue: 2, wound: "wound_corte_brazo_001" }, result_text: "Tu cabo vuelve con un tajo y la cara lavada." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["tavern", "duel"],
    },
    {
      id: "event_clima_lluvia_001",
      name: "Lluia interminable",
      description: "La lluvia no cesa. La pólvora se humedece y los hombres tiemblan bajo la lona.",
      choices: [
        { id: "cubrirse", label: "Cubrirse y esperar", effects: { fatigue: 4, items: [{ itemId: "consumable_polvora_humeda_001", quantity: 1 }] }, result_text: "Esperas. La lluvia se ríe." },
        { id: "marchar", label: "Marchar pese a todo", effects: { fatigue: 8, wound: "wound_hielo_001" }, result_text: "Márchas. Algún hombre cae con temblores." },
        { id: "improvisar", label: "Improvisar cobertizos", effects: { coins: -6, fatigue: -2, discipline: 1 }, result_text: "Pagas madera. La línea se seca." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["camp", "weather"],
    },
    {
      id: "event_clima_calor_001",
      name: "Calor de Italia",
      description: "El sol cae a plomo sobre el tercio. El agua sabe a cuero y la sed hace locuras.",
      choices: [
        { id: "descansar", label: "Descansar a la sombra", effects: { fatigue: -4, discipline: -1 }, result_text: "Descansáis. La línea se retrasa." },
        { id: "buscar_agua", label: "Buscar agua en la aldea", effects: { coins: -4, fatigue: 2, items: [{ itemId: "consumable_vino_001", quantity: 1 }] }, result_text: "Compráis vino. La sed se calma." },
        { id: "marchar_noche", label: "Marchar de noche", effects: { fatigue: 6, discipline: 2 }, result_text: "Márchais. El calor os deja en paz." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["italy", "weather"],
    },
    {
      id: "event_reconocimiento_001",
      name: "Reconocimiento del frente",
      description: "El maestre pide un reconocimiento antes del asalto. Tuertes hombres listos.",
      choices: [
        { id: "ir_tu", label: "Ir tú mismo", effects: { honor: 2, fatigue: 6, items: [{ itemId: "trinket_mapa_001", quantity: 1 }] }, result_text: "Vuelves con un mapa. Y un rasguño." },
        { id: "enviar_patron", label: "Enviar al patrón de la compañía", effects: { honor: 1, fatigue: 2, items: [{ itemId: "trinket_mapa_001", quantity: 1 }] }, result_text: "El patrón vuelve. Algo sabe." },
        { id: "saltar", label: "Saltarse el reconocimiento", effects: { honor: -2, fatigue: -2, wound: "wound_mano_001" }, result_text: "Entráis a ciegas. Algo va mal." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["recon", "flandes"],
    },
    {
      id: "event_pillaje_antes_001",
      name: "Pillaje antes del asalto",
      description: "Antes de tomar el baluarte, la tropa quiere saquear lo cercano. El sargento espera tu orden.",
      choices: [
        { id: "permitir", label: "Permitir el pillaje corto", effects: { coins: 12, corruption: 8, fatigue: -2, items: [{ itemId: "consumable_vino_001", quantity: 2 }] }, result_text: "Vuelven cargados. El sargento calla." },
        { id: "prohibir", label: "Prohibirlo", effects: { honor: 3, discipline: 2, fatigue: 4 }, result_text: "Callan. La línea está entera." },
        { id: "limitar_horas", label: "Limitar a una hora", effects: { coins: 4, corruption: 2, fatigue: 2 }, result_text: "Pillan poco. Vuelven a tiempo." },
      ],
      mature: true,
      presentation: "blurred",
      tags: ["siege", "loot"],
    },
    {
      id: "event_tropas_amigas_001",
      name: "Tropas amigas en el camino",
      description: "Os cruzáis con otra compañía del tercio. Sus hombres piden sal y noticias.",
      choices: [
        { id: "compartir", label: "Compartir sal y vino", effects: { honor: 1, coins: -2, items: [{ itemId: "consumable_salazon_001", quantity: 1 }] }, result_text: "Compartís. Os recuerdan." },
        { id: "vender", label: "Vender al doble", effects: { coins: 8, corruption: 4 }, result_text: "Venden caro. No os olvidan." },
        { id: "ignorar", label: "Pasar de largo", effects: { honor: -1, discipline: 1 }, result_text: "No habláis. La línea sigue." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["camp", "ally"],
    },
    {
      id: "event_pedernal_seco_001",
      name: "Pedernal seco",
      description: "El pedernal se ha gastado y nadie tiene chispa fiable para los arcabuces.",
      choices: [
        { id: "comprar", label: "Comprar al mercader local", effects: { coins: -8, items: [{ itemId: "consumable_piedra_001", quantity: 3 }] }, result_text: "Compras. Los arcabuces disparan." },
        { id: "recoger", label: "Recoger del arroyo", effects: { fatigue: 4, items: [{ itemId: "consumable_piedra_001", quantity: 1 }] }, result_text: "Recoges. Apenas sirve." },
        { id: "improvizar", label: "Improvisar con mecha larga", effects: { fatigue: 2, items: [{ itemId: "consumable_mecha_001", quantity: 1 }] }, result_text: "Más mecha. Menos sorpresa." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["camp", "powder", "firearm"],
    },
    {
      id: "event_rumor_motin_001",
      name: "Rumor de motín",
      description: "Un cabo te dice en voz baja que media compañía piensa pedir cuentas al maestre de campo.",
      choices: [
        { id: "avisar_maestre", label: "Avisar al maestre", effects: { honor: 2, fatigue: 2, corruption: 4 }, result_text: "Avisas. Los cabecillas son detenidos." },
        { id: "callar", label: "Callar y observar", effects: { honor: -1, discipline: -1 }, result_text: "Callas. Algo se mueve." },
        { id: "liderar", label: "Ponerte al frente del motín", effects: { honor: -3, corruption: 8, fatigue: 4 }, result_text: "Te pones al frente. El sargento no se atreve." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["camp", "mutiny"],
    },
    {
      id: "event_asedio_frio_001",
      name: "Frío del asedio",
      description: "La trinchera hiela y los hombres tiemblan. La línea aguanta o no aguanta.",
      choices: [
        { id: "rotar", label: "Rotar la línea más a menudo", effects: { fatigue: 2, discipline: 1, wound: "wound_hielo_001" }, result_text: "Rotan. El frío reparte." },
        { id: "aguardiente", label: "Repartir aguardiente", effects: { coins: -8, fatigue: -2, discipline: -1, items: [{ itemId: "consumable_aguardiente_001", quantity: 2 }] }, result_text: "Beben. La línea tiembla menos." },
        { id: "forzar", label: "Forzar la guardia", effects: { fatigue: 8, wound: "wound_fiebre_001" }, result_text: "La línea aguanta. Y cae." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["siege", "weather"],
    },
    {
      id: "event_obispo_001",
      name: "Pasa el obispo",
      description: "Un obispo del ejército llega a bendecir la línea. El capellán se alegra. Los hombres dudan.",
      choices: [
        { id: "recibir", label: "Recibirlo con honores", effects: { honor: 3, coins: -6 }, result_text: "La línea se arrodilla. El obispo bendice." },
        { id: "rechazar", label: "Rechazar la bendición", effects: { honor: -2, discipline: 1 }, result_text: "El obispo se va. Tus hombres callan." },
        { id: "negociar", label: "Pedir dinero por la bendición", effects: { coins: 12, corruption: 8, honor: -2 }, result_text: "Pagan. El capellán te mira raro." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["camp", "religion"],
    },
    {
      id: "event_traidor_en_linea_001",
      name: "Traidor en la línea",
      description: "Un cabo te dice que uno de tus hombres vende secretos al enemigo.",
      choices: [
        { id: "ejecutar", label: "Ejecutarlo en silencio", effects: { honor: 1, corruption: 6, discipline: 1 }, result_text: "Lo ahorcan. Nadie pregunta." },
        { id: "juzgar", label: "Juzgarlo ante la tropa", effects: { honor: 3, fatigue: 4, discipline: 2 }, result_text: "Lo juzgan. La tropa aprende." },
        { id: "usar", label: "Usarlo para engañar al enemigo", effects: { honor: -2, cunning: 2, items: [{ itemId: "trinket_mapa_001", quantity: 1 }] }, result_text: "Lo usas. Miente dos veces." },
      ],
      mature: true,
      presentation: "blurred",
      tags: ["line", "traitor"],
    },
    {
      id: "event_herido_critico_001",
      name: "Herido crítico en el campo",
      description: "Un compañero tiene una herida que no perdona. El cirujano duda.",
      choices: [
        { id: "amputar", label: "Amputar y salvar", effects: { coins: -12, wound: "wound_perdida_dedo_001" }, result_text: "Lo salva sin un dedo." },
        { id: "dejar_morir", label: "Dejarlo morir con un rezo", effects: { honor: -3, discipline: -1 }, result_text: "Rezas. Se va en silencio." },
        { id: "intentar_todo", label: "Intentar todo", effects: { coins: -20, fatigue: 4, items: [{ itemId: "consumable_unguento_001", quantity: 2 }] }, result_text: "Lo intenta. La bolsa queda vacía." },
      ],
      mature: true,
      presentation: "blurred",
      tags: ["camp", "wound"],
    },
    {
      id: "event_caravana_caida_001",
      name: "Caravana caída",
      description: "Una carreta volcada bloquea el camino. El conductor sangra.",
      choices: [
        { id: "auxiliar", label: "Auxiliar y robar algo", effects: { coins: 4, honor: -1, items: [{ itemId: "consumable_salazon_001", quantity: 1 }] }, result_text: "Le ayudas. Le cobras en especie." },
        { id: "robar_todo", label: "Robar todo", effects: { coins: 18, corruption: 8, honor: -3, items: [{ itemId: "consumable_pan_duro_001", quantity: 3 }] }, result_text: "Vuelves con comida. Y con vergüenza." },
        { id: "dejar_pasar", label: "Dejar pasar y marchar", effects: { honor: 1, discipline: 1 }, result_text: "Pasas. El conductor te maldice." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["road", "caravan"],
    },
    {
      id: "event_herencia_pelea_001",
      name: "Herencia de un muerto",
      description: "Un soldado muerto deja una bolsa con monedas y una carta. El cabo te la entrega.",
      choices: [
        { id: "entregar_familia", label: "Entregar a la familia", effects: { honor: 3, discipline: 1 }, result_text: "La línea entera lo sabe. Te respetan." },
        { id: "repartir_tropa", label: "Repartir entre la tropa", effects: { coins: 8, honor: 1, discipline: 1 }, result_text: "Repartes. Hay vino esa noche." },
        { id: "quedarte_todo", label: "Quedarte todo", effects: { coins: 18, corruption: 6, honor: -2 }, result_text: "Callas. El cabo sospecha." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["camp", "money"],
    },
    {
      id: "event_pelea_campamento_001",
      name: "Pelea en el campamento",
      description: "Dos soldados se agarran por una baraja. La sangre salpica la pica más cercana.",
      choices: [
        { id: "separar", label: "Separar y azotar a los dos", effects: { discipline: 1, corruption: 4, fatigue: 1 }, result_text: "Los azotan. Se miran con rencor." },
        { id: "ver", label: "Dejar que se desfoguen", effects: { discipline: -2, fatigue: -2, wound: "wound_mano_001" }, result_text: "Pelean. Se desfogan." },
        { id: "echar", label: "Echar a los dos del campamento", effects: { discipline: 2, fatigue: 4, honor: -1 }, result_text: "Se van. La línea descansa." },
      ],
      mature: false,
      presentation: "normal",
      tags: ["camp", "discipline"],
    },
  ];
}
