#!/usr/bin/env node
// lootTables.mjs — 18 loot tables for different mission tiers and regions.

export function buildLootTables() {
  return [
    {
      id: "loot_early_road_001",
      entries: [
        { itemId: "consumable_pan_duro_001", weight: 30, min: 1, max: 2 },
        { itemId: "material_tela_sucia_001", weight: 22, min: 1, max: 2 },
        { itemId: "trinket_moneda_001", weight: 18, min: 1, max: 3 },
        { itemId: "consumable_vendas_001", weight: 10, min: 1, max: 1 },
        { itemId: "weapon_daga_001", weight: 10, min: 1, max: 1 },
        { itemId: "material_hebilla_001", weight: 6, min: 1, max: 1 },
        { itemId: "religious_cruz_001", weight: 4, min: 1, max: 1 },
      ],
    },
    {
      id: "loot_watch_001",
      entries: [
        { itemId: "consumable_pan_duro_001", weight: 28, min: 1, max: 1 },
        { itemId: "material_tela_sucia_001", weight: 18, min: 1, max: 1 },
        { itemId: "trinket_moneda_001", weight: 14, min: 1, max: 2 },
        { itemId: "consumable_vino_001", weight: 12, min: 1, max: 1 },
        { itemId: "consumable_aceite_001", weight: 10, min: 1, max: 1 },
        { itemId: "consumable_vendas_001", weight: 8, min: 1, max: 1 },
        { itemId: "religious_rosario_001", weight: 6, min: 1, max: 1 },
        { itemId: "weapon_ropera_ronosa_001", weight: 4, min: 1, max: 1 },
      ],
    },
    {
      id: "loot_patrol_001",
      entries: [
        { itemId: "consumable_salazon_001", weight: 20, min: 1, max: 1 },
        { itemId: "consumable_vino_001", weight: 16, min: 1, max: 1 },
        { itemId: "trinket_moneda_001", weight: 14, min: 1, max: 3 },
        { itemId: "material_cuero_duro_001", weight: 12, min: 1, max: 1 },
        { itemId: "consumable_vendas_001", weight: 10, min: 1, max: 1 },
        { itemId: "weapon_cazoleta_001", weight: 8, min: 1, max: 1 },
        { itemId: "weapon_daga_001", weight: 6, min: 1, max: 1 },
        { itemId: "helmet_morion_001", weight: 6, min: 1, max: 1 },
        { itemId: "chest_cuirass_001", weight: 4, min: 1, max: 1 },
        { itemId: "trinket_mapa_001", weight: 4, min: 1, max: 1 },
      ],
    },
    {
      id: "loot_patrol_flandes_001",
      entries: [
        { itemId: "consumable_salazon_001", weight: 16, min: 1, max: 1 },
        { itemId: "consumable_vino_001", weight: 14, min: 1, max: 1 },
        { itemId: "consumable_mecha_001", weight: 12, min: 1, max: 2 },
        { itemId: "consumable_polvora_seca_001", weight: 10, min: 1, max: 1 },
        { itemId: "weapon_mecha_001", weight: 8, min: 1, max: 1 },
        { itemId: "chest_cuirass_004", weight: 8, min: 1, max: 1 },
        { itemId: "helmet_morion_004", weight: 6, min: 1, max: 1 },
        { itemId: "weapon_ancha_flandes_001", weight: 6, min: 1, max: 1 },
        { itemId: "trinket_mapa_001", weight: 6, min: 1, max: 1 },
        { itemId: "weapon_pica_ash_001", weight: 5, min: 1, max: 1 },
        { itemId: "gloves_buff_001", weight: 4, min: 1, max: 1 },
        { itemId: "religious_relicario_001", weight: 3, min: 1, max: 1 },
        { itemId: "chest_cuirass_005", weight: 2, min: 1, max: 1 },
      ],
    },
    {
      id: "loot_convoy_001",
      entries: [
        { itemId: "consumable_pan_duro_001", weight: 20, min: 2, max: 4 },
        { itemId: "consumable_salazon_001", weight: 16, min: 1, max: 2 },
        { itemId: "trinket_moneda_001", weight: 14, min: 2, max: 5 },
        { itemId: "consumable_vino_001", weight: 10, min: 1, max: 1 },
        { itemId: "material_cuero_duro_001", weight: 10, min: 1, max: 2 },
        { itemId: "consumable_polvora_seca_001", weight: 8, min: 1, max: 1 },
        { itemId: "weapon_pica_ash_001", weight: 6, min: 1, max: 1 },
        { itemId: "weapon_cazoleta_001", weight: 5, min: 1, max: 1 },
        { itemId: "chest_gambeson_u_001", weight: 4, min: 1, max: 1 },
        { itemId: "boots_official_001", weight: 3, min: 1, max: 1 },
        { itemId: "weapon_pica_sargento_001", weight: 2, min: 1, max: 1 },
        { itemId: "weapon_toledo_001", weight: 2, min: 1, max: 1 },
      ],
    },
    {
      id: "loot_powder_001",
      entries: [
        { itemId: "consumable_polvora_seca_001", weight: 22, min: 1, max: 2 },
        { itemId: "consumable_mecha_001", weight: 18, min: 1, max: 2 },
        { itemId: "consumable_plomo_001", weight: 14, min: 1, max: 2 },
        { itemId: "consumable_piedra_001", weight: 10, min: 1, max: 1 },
        { itemId: "weapon_mecha_001", weight: 10, min: 1, max: 1 },
        { itemId: "material_polvora_humeda_001", weight: 8, min: 1, max: 1 },
        { itemId: "weapon_curena_001", weight: 6, min: 1, max: 1 },
        { itemId: "weapon_rueda_001", weight: 4, min: 1, max: 1 },
        { itemId: "weapon_maestro_tirador_001", weight: 2, min: 1, max: 1 },
      ],
    },
    {
      id: "loot_skirmish_001",
      entries: [
        { itemId: "weapon_mecha_001", weight: 14, min: 1, max: 1 },
        { itemId: "weapon_ancha_flandes_001", weight: 12, min: 1, max: 1 },
        { itemId: "weapon_pica_ash_001", weight: 12, min: 1, max: 1 },
        { itemId: "helmet_morion_004", weight: 10, min: 1, max: 1 },
        { itemId: "chest_cuirass_004", weight: 10, min: 1, max: 1 },
        { itemId: "consumable_vendas_001", weight: 10, min: 1, max: 2 },
        { itemId: "gloves_buff_001", weight: 6, min: 1, max: 1 },
        { itemId: "weapon_pica_sargento_001", weight: 5, min: 1, max: 1 },
        { itemId: "weapon_toledo_001", weight: 4, min: 1, max: 1 },
        { itemId: "weapon_rueda_001", weight: 4, min: 1, max: 1 },
        { itemId: "religious_relicario_001", weight: 4, min: 1, max: 1 },
        { itemId: "chest_cuirass_rare_001", weight: 3, min: 1, max: 1 },
        { itemId: "helmet_morion_v_001", weight: 2, min: 1, max: 1 },
        { itemId: "weapon_pica_flandes_001", weight: 2, min: 1, max: 1 },
        { itemId: "weapon_veterana_001", weight: 2, min: 1, max: 1 },
      ],
    },
    {
      id: "loot_pay_001",
      entries: [
        { itemId: "trinket_moneda_001", weight: 22, min: 2, max: 6 },
        { itemId: "trinket_carta_001", weight: 16, min: 1, max: 1 },
        { itemId: "religious_relicario_001", weight: 10, min: 1, max: 1 },
        { itemId: "chest_cuirass_004", weight: 10, min: 1, max: 1 },
        { itemId: "weapon_pica_ash_001", weight: 8, min: 1, max: 1 },
        { itemId: "helmet_morion_004", weight: 6, min: 1, max: 1 },
        { itemId: "weapon_toledo_001", weight: 5, min: 1, max: 1 },
        { itemId: "chest_cuirass_rare_001", weight: 4, min: 1, max: 1 },
        { itemId: "weapon_pica_sargento_001", weight: 4, min: 1, max: 1 },
        { itemId: "religious_medalla_001", weight: 3, min: 1, max: 1 },
        { itemId: "trinket_mapa_001", weight: 3, min: 1, max: 1 },
      ],
    },
    {
      id: "loot_siege_001",
      entries: [
        { itemId: "weapon_pica_sargento_001", weight: 14, min: 1, max: 1 },
        { itemId: "weapon_toledo_001", weight: 12, min: 1, max: 1 },
        { itemId: "weapon_rueda_001", weight: 12, min: 1, max: 1 },
        { itemId: "chest_cuirass_rare_001", weight: 10, min: 1, max: 1 },
        { itemId: "helmet_morion_v_001", weight: 10, min: 1, max: 1 },
        { itemId: "weapon_pica_flandes_001", weight: 8, min: 1, max: 1 },
        { itemId: "weapon_veterana_001", weight: 6, min: 1, max: 1 },
        { itemId: "gloves_gauntlet_001", weight: 6, min: 1, max: 1 },
        { itemId: "boots_rare_001", weight: 5, min: 1, max: 1 },
        { itemId: "weapon_piston_001", weight: 5, min: 1, max: 1 },
        { itemId: "chest_gambeson_v_001", weight: 4, min: 1, max: 1 },
        { itemId: "religious_relicario_001", weight: 3, min: 1, max: 1 },
        { itemId: "weapon_pica_armero_001", weight: 3, min: 1, max: 1 },
        { itemId: "weapon_maestro_tirador_001", weight: 2, min: 1, max: 1 },
      ],
    },
    {
      id: "loot_boss_001",
      entries: [
        { itemId: "weapon_pica_sargento_001", weight: 10, min: 1, max: 1 },
        { itemId: "weapon_toledo_001", weight: 10, min: 1, max: 1 },
        { itemId: "weapon_rueda_001", weight: 10, min: 1, max: 1 },
        { itemId: "chest_cuirass_rare_001", weight: 8, min: 1, max: 1 },
        { itemId: "helmet_morion_v_001", weight: 8, min: 1, max: 1 },
        { itemId: "weapon_pica_flandes_001", weight: 7, min: 1, max: 1 },
        { itemId: "weapon_veterana_001", weight: 6, min: 1, max: 1 },
        { itemId: "weapon_piston_001", weight: 6, min: 1, max: 1 },
        { itemId: "gloves_gauntlet_001", weight: 5, min: 1, max: 1 },
        { itemId: "boots_rare_001", weight: 5, min: 1, max: 1 },
        { itemId: "trinket_mapa_001", weight: 4, min: 1, max: 1 },
        { itemId: "chest_gambeson_v_001", weight: 4, min: 1, max: 1 },
        { itemId: "religious_relicario_001", weight: 3, min: 1, max: 1 },
        { itemId: "weapon_pica_armero_001", weight: 3, min: 1, max: 1 },
        { itemId: "weapon_maestro_tirador_001", weight: 3, min: 1, max: 1 },
        { itemId: "helmet_morion_v_002", weight: 2, min: 1, max: 1 },
        { itemId: "weapon_tizona_001", weight: 1, min: 1, max: 1 },
      ],
    },
    {
      id: "loot_masterwork_001",
      entries: [
        { itemId: "weapon_pica_armero_001", weight: 10, min: 1, max: 1 },
        { itemId: "weapon_tizona_001", weight: 10, min: 1, max: 1 },
        { itemId: "weapon_maestro_tirador_001", weight: 8, min: 1, max: 1 },
        { itemId: "chest_cuirass_veteran_001", weight: 8, min: 1, max: 1 },
        { itemId: "helmet_morion_v_001", weight: 6, min: 1, max: 1 },
        { itemId: "chest_gambeson_v_001", weight: 5, min: 1, max: 1 },
        { itemId: "gloves_master_001", weight: 5, min: 1, max: 1 },
        { itemId: "boots_rare_001", weight: 4, min: 1, max: 1 },
        { itemId: "weapon_asedio_001", weight: 4, min: 1, max: 1 },
        { itemId: "chest_cuirass_master_001", weight: 3, min: 1, max: 1 },
        { itemId: "helmet_morion_master_001", weight: 3, min: 1, max: 1 },
        { itemId: "boots_master_001", weight: 3, min: 1, max: 1 },
        { itemId: "weapon_maestre_001", weight: 3, min: 1, max: 1 },
        { itemId: "weapon_pica_capitan_001", weight: 2, min: 1, max: 1 },
        { itemId: "chest_cuirass_rare_001", weight: 6, min: 1, max: 1 },
      ],
    },
    {
      id: "loot_italy_001",
      entries: [
        { itemId: "weapon_ancha_flandes_001", weight: 10, min: 1, max: 1 },
        { itemId: "weapon_pica_ash_001", weight: 10, min: 1, max: 1 },
        { itemId: "weapon_mecha_001", weight: 8, min: 1, max: 1 },
        { itemId: "helmet_morion_005", weight: 6, min: 1, max: 1 },
        { itemId: "chest_gambeson_u_002", weight: 6, min: 1, max: 1 },
        { itemId: "consumable_vino_001", weight: 6, min: 1, max: 2 },
        { itemId: "consumable_salazon_001", weight: 6, min: 1, max: 1 },
        { itemId: "weapon_pica_sargento_001", weight: 5, min: 1, max: 1 },
        { itemId: "weapon_toledo_001", weight: 5, min: 1, max: 1 },
        { itemId: "weapon_rueda_001", weight: 5, min: 1, max: 1 },
        { itemId: "chest_cuirass_rare_001", weight: 4, min: 1, max: 1 },
        { itemId: "helmet_morion_v_001", weight: 4, min: 1, max: 1 },
        { itemId: "weapon_pica_flandes_001", weight: 4, min: 1, max: 1 },
        { itemId: "weapon_veterana_001", weight: 3, min: 1, max: 1 },
        { itemId: "gloves_gauntlet_001", weight: 3, min: 1, max: 1 },
        { itemId: "boots_rare_001", weight: 2, min: 1, max: 1 },
      ],
    },
    {
      id: "loot_boy_initial_001",
      entries: [
        { itemId: "weapon_pica_gastada_001", weight: 1, min: 1, max: 1 },
        { itemId: "consumable_pan_duro_001", weight: 1, min: 2, max: 3 },
        { itemId: "consumable_vendas_001", weight: 1, min: 1, max: 1 },
        { itemId: "trinket_moneda_001", weight: 1, min: 10, max: 25 },
      ],
    },
    {
      id: "loot_tavern_001",
      entries: [
        { itemId: "consumable_aguardiente_001", weight: 24, min: 1, max: 1 },
        { itemId: "consumable_vino_001", weight: 18, min: 1, max: 1 },
        { itemId: "trinket_moneda_001", weight: 14, min: 1, max: 3 },
        { itemId: "weapon_daga_001", weight: 12, min: 1, max: 1 },
        { itemId: "material_hebilla_001", weight: 10, min: 1, max: 1 },
        { itemId: "religious_medalla_001", weight: 6, min: 1, max: 1 },
        { itemId: "trinket_carta_001", weight: 6, min: 1, max: 1 },
        { itemId: "weapon_ropera_ronosa_001", weight: 4, min: 1, max: 1 },
      ],
    },
    {
      id: "loot_forest_001",
      entries: [
        { itemId: "consumable_salazon_001", weight: 20, min: 1, max: 1 },
        { itemId: "consumable_vino_001", weight: 14, min: 1, max: 1 },
        { itemId: "consumable_mecha_001", weight: 10, min: 1, max: 1 },
        { itemId: "consumable_polvora_seca_001", weight: 8, min: 1, max: 1 },
        { itemId: "material_cuero_duro_001", weight: 8, min: 1, max: 1 },
        { itemId: "trinket_moneda_001", weight: 6, min: 1, max: 2 },
        { itemId: "weapon_daga_001", weight: 6, min: 1, max: 1 },
        { itemId: "weapon_mecha_001", weight: 4, min: 1, max: 1 },
        { itemId: "consumable_piedra_001", weight: 4, min: 1, max: 1 },
        { itemId: "weapon_pica_corta_001", weight: 4, min: 1, max: 1 },
        { itemId: "chest_gambeson_001", weight: 3, min: 1, max: 1 },
        { itemId: "gloves_001", weight: 2, min: 1, max: 1 },
        { itemId: "weapon_cazoleta_001", weight: 2, min: 1, max: 1 },
      ],
    },
    {
      id: "loot_camp_001",
      entries: [
        { itemId: "consumable_pan_duro_001", weight: 20, min: 1, max: 2 },
        { itemId: "consumable_salazon_001", weight: 14, min: 1, max: 1 },
        { itemId: "consumable_aceite_001", weight: 12, min: 1, max: 1 },
        { itemId: "consumable_vendas_001", weight: 10, min: 1, max: 1 },
        { itemId: "consumable_aguja_001", weight: 8, min: 1, max: 1 },
        { itemId: "material_hebilla_001", weight: 8, min: 1, max: 1 },
        { itemId: "material_cuero_duro_001", weight: 6, min: 1, max: 1 },
        { itemId: "consumable_vino_001", weight: 5, min: 1, max: 1 },
        { itemId: "consumable_unguento_001", weight: 4, min: 1, max: 1 },
        { itemId: "weapon_daga_001", weight: 3, min: 1, max: 1 },
        { itemId: "gloves_001", weight: 3, min: 1, max: 1 },
        { itemId: "boots_001", weight: 2, min: 1, max: 1 },
      ],
    },
    {
      id: "loot_ammo_supply_001",
      entries: [
        { itemId: "consumable_polvora_seca_001", weight: 24, min: 2, max: 3 },
        { itemId: "consumable_plomo_001", weight: 20, min: 2, max: 3 },
        { itemId: "consumable_mecha_001", weight: 18, min: 1, max: 2 },
        { itemId: "consumable_piedra_001", weight: 12, min: 1, max: 2 },
        { itemId: "material_polvora_humeda_001", weight: 10, min: 1, max: 1 },
        { itemId: "weapon_mecha_001", weight: 6, min: 1, max: 1 },
        { itemId: "weapon_curena_001", weight: 4, min: 1, max: 1 },
        { itemId: "weapon_rueda_001", weight: 2, min: 1, max: 1 },
      ],
    },
    {
      id: "loot_chest_001",
      entries: [
        { itemId: "trinket_moneda_001", weight: 22, min: 5, max: 12 },
        { itemId: "trinket_carta_001", weight: 14, min: 1, max: 2 },
        { itemId: "religious_relicario_001", weight: 10, min: 1, max: 1 },
        { itemId: "consumable_vino_001", weight: 10, min: 1, max: 1 },
        { itemId: "consumable_salazon_001", weight: 8, min: 1, max: 2 },
        { itemId: "chest_cuirass_004", weight: 6, min: 1, max: 1 },
        { itemId: "weapon_pica_ash_001", weight: 5, min: 1, max: 1 },
        { itemId: "helmet_morion_004", weight: 4, min: 1, max: 1 },
        { itemId: "religious_medalla_001", weight: 3, min: 1, max: 1 },
        { itemId: "trinket_mapa_001", weight: 3, min: 1, max: 1 },
        { itemId: "weapon_toledo_001", weight: 2, min: 1, max: 1 },
        { itemId: "chest_cuirass_rare_001", weight: 2, min: 1, max: 1 },
      ],
    },
  ];
}
