#!/usr/bin/env node
// wounds.mjs — 20 wounds from minor cuts to grave injuries.

export function buildWounds() {
  return [
    { id: "wound_corte_mano_001", name: "Corte en la mano", severity: "minor", description: "Corte superficial en los nudillos. Duele al empuñar.", effects: { sword: -1, pike: 0, arquebus: 0, vigor: 0, discipline: 0 }, healingCost: 6, healingHours: 2, treatmentItems: ["consumable_vendas_001"], mature: false, presentation: "normal" },
    { id: "wound_corte_brazo_001", name: "Corte en el brazo", severity: "minor", description: "Brazo sangrante, agarra peor el arma.", effects: { sword: -1, arquebus: -1 }, healingCost: 8, healingHours: 3, treatmentItems: ["consumable_vendas_001"], mature: false, presentation: "normal" },
    { id: "wound_quemadura_001", name: "Quemadura de pólvora", severity: "moderate", description: "Mano ennegrecida por chispa de arcabuz.", effects: { arquebus: -1, vigor: -1 }, healingCost: 12, healingHours: 4, treatmentItems: ["consumable_unguento_001"], mature: false, presentation: "normal" },
    { id: "wound_esguince_001", name: "Esguince de tobillo", severity: "minor", description: "Tobillo torcido. Cada paso cuesta más.", effects: { vigor: -1, pike: -1 }, healingCost: 8, healingHours: 3, treatmentItems: ["material_tablilla_001"], mature: false, presentation: "normal" },
    { id: "wound_costilla_001", name: "Costilla rota", severity: "serious", description: "Respirar duele, toser castiga.", effects: { vigor: -2, pike: -1 }, healingCost: 24, healingHours: 12, treatmentItems: ["consumable_vendas_001", "material_tablilla_001"], mature: false, presentation: "normal" },
    { id: "wound_infeccion_001", name: "Herida infectada", severity: "serious", description: "Calor bajo la piel y miedo en las palabras.", effects: { vigor: -2, discipline: -1 }, healingCost: 30, healingHours: 24, treatmentItems: ["consumable_unguento_001", "consumable_vendas_001"], mature: true, presentation: "blurred" },
    { id: "wound_oido_001", name: "Daño auditivo", severity: "minor", description: "Las órdenes llegan entre un zumbido sordo.", effects: { command: -1, discipline: -1 }, healingCost: 10, healingHours: 6, treatmentItems: ["consumable_vendas_001"], mature: false, presentation: "normal" },
    { id: "wound_mano_001", name: "Mano magullada", severity: "minor", description: "Nudillos morados, mal agarre.", effects: { sword: -1, arquebus: -1 }, healingCost: 8, healingHours: 4, treatmentItems: ["consumable_vendas_001"], mature: false, presentation: "normal" },
    { id: "wound_moral_001", name: "Moral quebrantada", severity: "moderate", description: "La línea resistió, pero solo por fuera.", effects: { discipline: -2, command: -1 }, healingCost: 14, healingHours: 8, treatmentItems: ["consumable_vino_001"], mature: false, presentation: "normal" },
    { id: "wound_fiebre_001", name: "Fiebre de campamento", severity: "serious", description: "Sudor, rezos y olor a paja mojada.", effects: { vigor: -2, discipline: -1 }, healingCost: 20, healingHours: 12, treatmentItems: ["consumable_vino_001", "consumable_vendas_001"], mature: false, presentation: "normal" },
    { id: "wound_bala_pierna_001", name: "Balazo en la pierna", severity: "serious", description: "Plomo alojado en el muslo. Arrastras la pierna.", effects: { vigor: -2, pike: -1, sword: -1 }, healingCost: 35, healingHours: 18, treatmentItems: ["consumable_unguento_001", "consumable_vendas_001"], mature: true, presentation: "blurred" },
    { id: "wound_pica_hombro_001", name: "Pica en el hombro", severity: "moderate", description: "Punta de pica en el hombro. Cuesta alzar el brazo.", effects: { pike: -2, arquebus: -1 }, healingCost: 18, healingHours: 8, treatmentItems: ["consumable_vendas_001", "consumable_unguento_001"], mature: false, presentation: "normal" },
    { id: "wound_cabeza_001", name: "Golpe en la cabeza", severity: "moderate", description: "Morrion abollado y la cabeza zumba.", effects: { discipline: -1, cunning: -1 }, healingCost: 12, healingHours: 6, treatmentItems: ["consumable_vendas_001"], mature: false, presentation: "normal" },
    { id: "wound_desgarro_001", name: "Desgarro muscular", severity: "moderate", description: "Muslo desgarrado. No corres, no peleas como antes.", effects: { vigor: -1, pike: -1, sword: -1 }, healingCost: 16, healingHours: 10, treatmentItems: ["consumable_unguento_001"], mature: false, presentation: "normal" },
    { id: "wound_hielo_001", name: "Congelación", severity: "moderate", description: "Dedos blancos, no sientes el arma.", effects: { arquebus: -1, sword: -1, vigor: -1 }, healingCost: 14, healingHours: 8, treatmentItems: ["consumable_vendas_001"], mature: false, presentation: "normal" },
    { id: "wound_mordedura_001", name: "Mordedura de rata", severity: "minor", description: "Diente de rata en el dedo. Hinchado y sucio.", effects: { vigor: -1 }, healingCost: 10, healingHours: 6, treatmentItems: ["consumable_unguento_001"], mature: true, presentation: "blurred" },
    { id: "wound_diarrea_001", name: "Diarrea de campaña", severity: "minor", description: "Tripas sueltas. Mal día para revista.", effects: { discipline: -1, vigor: -1 }, healingCost: 6, healingHours: 4, treatmentItems: ["consumable_vino_001"], mature: true, presentation: "blurred" },
    { id: "wound_corte_grave_001", name: "Corte profundo", severity: "grave", description: "Una herida que se abre al moverse. La línea se abre contigo.", effects: { vigor: -2, sword: -1, pike: -1 }, healingCost: 40, healingHours: 24, treatmentItems: ["consumable_vendas_001", "consumable_unguento_001", "consumable_aguja_001"], mature: true, presentation: "blurred" },
    { id: "wound_perdida_dedo_001", name: "Dedo perdido", severity: "moderate", description: "Dedo cortado. Empuñar duele.", effects: { sword: -2, arquebus: -1 }, healingCost: 20, healingHours: 12, treatmentItems: ["consumable_vendas_001"], mature: true, presentation: "blurred" },
    { id: "wound_psicologica_001", name: "Temblor de después", severity: "moderate", description: "Tiemblas cuando oyes un disparo. La línea se entera.", effects: { discipline: -2, command: -1, arquebus: -1 }, healingCost: 18, healingHours: 10, treatmentItems: ["consumable_vino_001"], mature: false, presentation: "normal" },
  ];
}
